### ISSUE TITLE
Avoid using word "Alerting" to prevent confusion with CAP

### ISSUE THREAD

**Issue by josusky** [wmo-im/wis2-monitoring-events#1]
As the specification is based on CloudEvents it seems appropriate to call it something like "WIS2 Monitoring Events". Then the "WIS2 Alerting Hierarchy" could be renamed to, err, "WIS2 Monitoring Event Topic". Because it is not really a hierarchical tree but a topic constructed from 5 values where the first 3 are fixed and the last two are from the same code table (list of centre IDs).

**Comment by tomkralidis** [comment]
@josusky thanks for the input.

- specification renamed to "WIS2 Monitoring Events"
- topic requirements/conformance renamed to "WIS2 Monitoring Event Topic"

Closing for now.  Please let me know if there's anything I missed in the rename.
